export const EP = {
  auth: {
    login: '/v1/auth/login',
    otpRequest: '/v1/auth/otp/request',
    otpVerify: '/v1/auth/otp/verify',
    refresh: '/v1/auth/refresh',
    logout: '/v1/auth/logout',
  },
  uploads: {
    presign: '/v1/uploads/presign',
  },
  admin: {
    companies: '/v1/admin/companies',
    companyDetail: (id: string) => `/v1/admin/companies/${id}/detail`,
    companyApprove: (id: string) => `/v1/admin/companies/${id}/approve`,
    companySuspend: (id: string) => `/v1/admin/companies/${id}/suspend`,
    companyCommission: (id: string) => `/v1/admin/companies/${id}/commission`,
    orders: '/v1/admin/orders',
    orderIntervene: (id: string) => `/v1/admin/orders/${id}/intervene`,
    categories: '/v1/admin/catalog/categories',
    category: (id: string) => `/v1/admin/catalog/categories/${id}`,
    services: '/v1/admin/catalog/services',
    service: (id: string) => `/v1/admin/catalog/services/${id}`,
    coupons: '/v1/admin/coupons',
    coupon: (id: string) => `/v1/admin/coupons/${id}`,
    banners: '/v1/admin/banners',
    banner: (id: string) => `/v1/admin/banners/${id}`,
    settlements: '/v1/admin/settlements',
    settlementApprove: (id: string) => `/v1/admin/settlements/${id}/approve`,
    settlementVoid: (id: string) => `/v1/admin/settlements/${id}/void`,
    reportsSales: '/v1/admin/reports/sales',
    audit: '/v1/admin/audit',
    users: '/v1/admin/users',
    user: (id: string) => `/v1/admin/users/${id}`,
    userStatus: (id: string) => `/v1/admin/users/${id}/status`,
  },
  provider: {
    company: '/v1/provider/me/company',
    financials: '/v1/provider/me/financials',
    staff: '/v1/provider/me/staff',
    staffOne: (id: string) => `/v1/provider/me/staff/${id}`,
    orders: '/v1/provider/me/orders',
    orderAssign: (id: string) => `/v1/provider/me/orders/${id}/assign`,
    settlements: '/v1/provider/me/settlements',
    settlementPdf: (id: string) =>
      `/v1/provider/me/settlements/${id}/statement.pdf`,
  },
  bookings: {
    one: (id: string) => `/v1/bookings/${id}`,
    status: (id: string) => `/v1/bookings/${id}/status`,
    cancel: (id: string) => `/v1/bookings/${id}/cancel`,
  },
} as const;
